### ISSUE TITLE
Task: Create endpoint that will delete any entries in database associated with the leaving user

### ISSUE THREAD

**Issue by kwang38** [xlab-classes/cse442-spring2022-team-APlus#15]
Task test 1:

Create a profile
Upload a listing to /listing
Upload a profile picture on /upload
Delete your profile at the same endpoint
Verify that you cannot visit other endpoints that require accounts such /listing and /upload

**Comment by Ncohen10** [comment]
Task test: 
- Signup and register a profile at the /signup and /login endpoints respectively.
- Go to the /listing endpoint and make a post
- Go to the /upload endpoint and press the button that specifies profile deletion
- Repeat step 1
- Go to the /listing endpoint and assert that the post you previously made does not exist.
