### ISSUE TITLE
User Story: As a user, I want to be able to delete my account and any information I added to the site so that I can ensure my data privacy

### ISSUE THREAD

**Issue by kwang38** [xlab-classes/cse442-spring2022-team-APlus#5]
Acceptance test 1:

Navigate to the /delete_profile endpoint without having an account.
Assert that you are redirected to login/signup page and that and error isn't thrown.

Acceptance test 2:

Signup and register a profile at the /signup and /login endpoints respectively.
Go to the /listing endpoint and make a post
Go to the /upload endpoint and press the button that specifies profile deletion
Repeat step 1
Go to the /listing endpoint and assert that the post you previously made does not exist.

**Comment by Ncohen10** [comment]
Task test: 
- Signup and register a profile at the /signup and /login endpoints respectively.
- Go to the /listing endpoint and make a post
- Go to the /upload endpoint and press the button that specifies profile deletion
- Repeat step 1
- Go to the /listing endpoint and assert that the post you previously made does not exist.
