### ISSUE TITLE
As a user, I want to be able to save or like a post so that I can show my interest and go back and be able to quickly revisit the listings

### ISSUE THREAD

**Issue by jing-chi** [xlab-classes/cse442-spring2022-team-APlus#6]
**Acceptance Tests:**

**Acceptance Test 1 - Liking a Post**
1. From the login page (/login), log in with the email "kwang38@buffalo.edu" and password "Testing"
2. Verify that you are brought to the profile by checking that the page title displays "User Profile"
3. From the navigation bar, click on the navigation element "Posts"
4. Verify that you are brought to the listings page by checking that the endpoint is "/listing"
5. Find a post you want to like. Keep track of the like counter displayed under the listing description
6. Click on the button that says "Like/Unlike Post"
7. Find the listing and verify that the like counter has updated.
8. Click on the button that says "Like/Unlike Post"
9. Verify that the like counter has updated to the original count (unliking a post)

**Acceptance Test 2 - Saving a Post**

1. From the login page (/login), log in with the email "kwang38@buffalo.edu" and password "Testing"
2. Verify that you are brought to the profile by checking that the page title displays "User Profile"
3. From the navigation bar, click on the navigation element "Posts"
4. Verify that you are brought to the listings page by checking that the endpoint is "/listing"
5. Find a post that you want to save. Then, click on the "Save Post" button
6. Navigate to the saved post page (/view_saved)
7. Verify that you are on the saved post page by verifying that page title displays "saved"
8. Verify that the post saved from step 5 is visible on the saved post page

**Comment by Ncohen10** [comment]
**Acceptance Tests:**

*Test 1*
1) Once logged in, create a housing post on the listing page
2) Like the post
3) Unlike the post
4) Ensure the post has 0 likes

*Test 2*
1) Once logged in, create a housing post on the listing page
2) Like the post
3) Ensure the post has 1 like

*Test 3*
1) Once logged in, create a housing post on the listing page
2) Save the post
3) Go to the profile page and click view saved
4) Ensure that the original saved post is there with the same description, name, and image.

**Comment by Ncohen10** [comment]
This user story is associated with tasks #54 and #55
