### ISSUE TITLE
User Story: As a user, I want to be able to take down any previous openings I posted up before so that other users will no longer see it

### ISSUE THREAD

**Issue by BuffetRacoon** [xlab-classes/cse442-spring2022-team-APlus#9]
Acceptance test:

1.  type "post 1" in the title in the text box
2. type "housing" in the description  in the text box
3.  choose a file that you want to upload (this file should be 'png' or 'jpg' or 'jpeg')
4.  click the button posts (your file, title and description will appear under the Listings header)
5. There will be a Delete button on bottom of your uploaded file
6.  click on the Delete button ( your posts will be deleted where the post will disappear)

**Comment by jing-chi** [comment]
Task test:
1) Login to you account
2)change the url to http://localhost:5000/listing
3) fill in the text box for title and description 
4) choose a file
5) click posts (you file, title and description will appear under the Listings header)
6) There will be a Delete button under you uploaded file
7) click on the Delete button  and your posts will be deleted
